# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

**Print out the dimension (number of axes), shape, size and the datatype of the matrix A.**

In [3]:
A = np.arange(1, 16).reshape(3,5)

print("Matris A:")
print(A)

print("\nDimension (number of axes) :", A.ndim)
print("Shape (shape) :", A.shape)
print("Size (Total number elements) :", A.size)
print("Datatype :", A.dtype)

Matris A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Dimension (number of axes) : 2
Shape (shape) : (3, 5)
Size (Total number elements) : 15
Datatype : int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
X = np.subtract(B, C)
print(X)

print("*********************")

Z = np.multiply(B, C)
print(Z)

print("*********************")
D = B @ C
print(D)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
*********************
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
*********************
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
np.set_printoptions(suppress=True)

A= np.exp(B)
print("\n", A)

min_value = np.min(A)
print("\nMinimum Value in the Whole Matrix:", min_value)

min_value_row = np.min(A, axis=1,)
print("\nMinimum Value in each row:", min_value_row)

min_value_column = np.min(A, axis=0,)
print("\nMinimum Value in each column:", min_value_column)



[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[   2.71828183    7.3890561    20.08553692]
 [  54.59815003  148.4131591   403.42879349]
 [1096.63315843 2980.95798704 8103.08392758]]

Minimum Value in the Whole Matrix: 2.718281828459045

Minimum Value in each row: [   2.71828183   54.59815003 1096.63315843]

Minimum Value in each column: [ 2.71828183  7.3890561  20.08553692]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[   2.71828183    7.3890561    20.08553692]
 [  54.59815003  148.4131591   403.42879349]
 [1096.63315843 2980.95798704 8103.08392758]]


In [9]:
A[1]

array([ 54.59815003, 148.4131591 , 403.42879349])

**Answer:**


### When fewer indices are provided than the number of axes, the missing indices are considered complete slices 

```python
I detta fall Numpy tolkar som att jag vill ha alla världen från den axeln. 
```

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [10]:
A

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [  54.59815003,  148.4131591 ,  403.42879349],
       [1096.63315843, 2980.95798704, 8103.08392758]])

In [11]:
for i in A:
    print(i)

[ 2.71828183  7.3890561  20.08553692]
[ 54.59815003 148.4131591  403.42879349]
[1096.63315843 2980.95798704 8103.08392758]


In [12]:
#Jag presenterar två metoder: 

for elementhwise in np.nditer(A):
   print(elementhwise) # np.nditer är em Kraftfull iterator och den är mutable.


print("*********************")

for element in A.flat:
    print(element) #b.flat iterator är enkel, immutable.

2.718281828459045
7.38905609893065
20.085536923187668
54.598150033144236
148.4131591025766
403.4287934927351
1096.6331584284585
2980.9579870417283
8103.083927575384
*********************
2.718281828459045
7.38905609893065
20.085536923187668
54.598150033144236
148.4131591025766
403.4287934927351
1096.6331584284585
2980.9579870417283
8103.083927575384


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [13]:
a = np.arange(30)

b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


np.arange(30) genererar ett fält(array) med heltalen från 0 till 29, det ökar med 1 per element eftersom vi inte har speciefierat start och step så python skriver ut alla värden från 0 till 29

b = a.reshape((2, 3, -1)) reshape betyder att vi kan ändra formen på array till olika dimensioner. 2 representer två block och 3 betyder tre rader, -1  är för att Python ska bestämma dimensioner automatiskt.

print a och är utskrift eller output. print() ger mellanrum mellan två resultat.


# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [14]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [15]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [16]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [17]:
import numpy as np

def add_mult_matrices (M1, M2, add_and_mult):
    if not isinstance(M1, np.ndarray) or not isinstance(M2, np.ndarray):
        raise ValueError("Både ingångar måste vara av type numpy.ndarray")
    
    if add_and_mult not in ['add', 'multiply']:
        raise ValueError("Operationen måste vara antingen 'lägg till' eller 'multiplicera'.")
    
    if add_and_mult == 'add':
        if M1.shape != M2.shape:
            raise ValueError("För matrisaddition måste båda matriserna ha samma storlek.")
        return M1 + M2
    
    elif add_and_mult == 'multiply':
        if M1.ndim == 1:  
            M1 = M1[:, np.newaxis] 
        if M2.ndim == 1:  
            M2 = M2[np.newaxis, :]  
        
        if M1.shape[1] != M2.shape[0]:
            raise ValueError("För att produkten M1M2 ska vara definierad måste antalet kolumner i M1 vara lika med antalet rader i M2.")
        
        return np.dot(M1, M2)




### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [18]:
print("Uppgift10.1.1:")
#a
print()
M1= np.array([4, 3])
X = M1
print(f"Dimension: {X.ndim}, Shape: {X.shape}")
#b
Z = np.array([[5]])
result1 = add_mult_matrices(Z, X, 'multiply')
print(result1)
#c
Z1 = np.array([[3]])
result2 = add_mult_matrices(Z1, X, 'multiply')
print(result2)
#d
print(result1+result2)
#e
Z2 = np.array([[8]])
result3 = add_mult_matrices(Z2, X, 'multiply')
print(result3)
#f
Z3 = np.array([[4]])
result4 = add_mult_matrices(Z3, X, 'multiply')
print(result4)
print(result4-X)
#g
X_T = X.reshape(-1,1)
print(X_T)
#h
try:
    result_X = add_mult_matrices(X, X_T, 'add')  
    print(result_X)
except ValueError as e:
    print(f"Fel: {e}") 
#i
print()
result_i = np.linalg.norm(X, ord=2)
print(int(result_i))
#koden kan skrivas så här också
norm_X = int(np.linalg.norm(X))
print(norm_X)

Uppgift10.1.1:

Dimension: 1, Shape: (2,)
[[20 15]]
[[12  9]]
[[32 24]]
[[32 24]]
[[16 12]]
[[12  9]]
[[4]
 [3]]
Fel: För matrisaddition måste båda matriserna ha samma storlek.

5
5


In [19]:
print("Uppgift 10.1.2:")
#a
print()
v = np.array([3, 7, 0, 11])
vektor = v.reshape(4, 1)
print(vektor)
print()
print(f"Dimension: {vektor.ndim}, Form: {vektor.shape}")

#b
v1= 2*vektor
print(v1)
#c
print()
v2= 5*vektor
print(v2+v1)
#d
print()
v4= 4*vektor
print(v4-v1)

print(v,)

#e
print()
vektor2 = vektor.reshape(4,1)
print(f"Dimension: {vektor2.ndim}, Form: {vektor2.shape}")

#f
print()
result_f = np.linalg.norm(v, ord=2)
print((result_f))


Uppgift 10.1.2:

[[ 3]
 [ 7]
 [ 0]
 [11]]

Dimension: 2, Form: (4, 1)
[[ 6]
 [14]
 [ 0]
 [22]]

[[21]
 [49]
 [ 0]
 [77]]

[[ 6]
 [14]
 [ 0]
 [22]]
[ 3  7  0 11]

Dimension: 2, Form: (4, 1)

13.379088160259652


In [20]:
print("Uppgift 10.1.3:")

v_1 = np.array([4, 3, 1, 5])
v_2 = np.array([2, 3, 1, 1])
print()
result_a = np.linalg.norm(v_1, ord=2)
print((result_a))

result_b = np.linalg.norm(v_2, ord=2)

result_c = np.linalg.norm(v_1-v_2, ord=2)
print(result_c)

Uppgift 10.1.3:

7.14142842854285
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [21]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B=  np.array([[4, -2, 1], [2, -4, -2]])
C=  np.array([[1, 2], [2, 1]])
D=  np.array([[3, 4], [4, 3]])
E=  np.array([[1,2]])
I=  np.array([[1, 0], [0, 1]])


result_a = 2 * A
result_b = B - 2 * A
#c är ej definierat
if C.shape == E.shape:
    result_C = 3*C-2*E
else:
    result_c = "Ej definierat"   

result_d = 2 * D - 3 * C
result_e = D.T + 2 * D
result_f = 2*C.T - 2*D.T
#result_g = A.T - B
if A.T.shape == B.shape:
    result_g = A.T - B
else:
    result_g = "Ej definierat"     
  
  
if A.shape == C.shape:
    result_h = A*C
else:
    result_h = "Ej definierat"   

result_i = np.dot(C, D)

result_j = np.dot(C, B)
result_k = np.dot(C, I)
result_l = np.dot(A, B.T)
# Skriv ut resultaten
print("a)", result_a)
print()
print("b)", result_b)
print()
print("C)", result_c)
print()
print("d)", result_d)
print()
print("e)", result_e)
print()
print("f)", result_f)
print()
print("g)", result_g)
print()
print("h)", result_h)
print() 
print("i)", result_i)
print() 
print("j)", result_j)
print() 
print("k)", result_k)
print() 
print("l)", result_l)

a) [[ 4  2 -2]
 [ 2 -2  2]]

b) [[ 0 -4  3]
 [ 0 -2 -4]]

C) Ej definierat

d) [[3 2]
 [2 3]]

e) [[ 9 12]
 [12  9]]

f) [[-4 -4]
 [-4 -4]]

g) Ej definierat

h) Ej definierat

i) [[11 10]
 [10 11]]

j) [[  8 -10  -3]
 [ 10  -8   0]]

k) [[1 2]
 [2 1]]

l) [[5 2]
 [7 4]]


In [24]:
print("uppgift 10.2.2:")

A = np.array([[2, 3, 4], [5, 4, 1]])
resultat = np.dot(A, A.T)
print(resultat)

uppgift 10.2.2:
[[29 26]
 [26 42]]


In [37]:
print("uppgift 10.2.4:")

def jämföra(A, B, C):
    if np.array_equal(AB, AC):
      return "AB = AC"
    else:
      return "AB ≠ AC"

result = jämföra(A, B, C)

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 1]])

AB = np.dot(A, B)
AC = np.dot(A, C)

print(AB)
print(AC)
print(result)

uppgift 10.2.4:
[[ 4  7]
 [ 8 14]]
[[ 4  5]
 [ 8 10]]
AB ≠ AC


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [57]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)
#If you change the last element in v2 to 123, will the last element in v1 be changed? Why?
""" It means that v2 refers to the same data as v1"""



[0 1 2 3]
[2 3]


' It means that v2 refers to the same data as v1'

In [56]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

"""If it is a view, v2.base will refer to v1. If it is a copy, v2.base will be None."""

None
[  0   1   2 123]


'If it is a view, v2.base will refer to v1. If it is a copy, v2.base will be None.'

In [55]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

""" Yes, bc both refers to the same data. When we change the value in v2 wich is a view of v1 it will affect v1"""

[  0   1   2 123]
[  2 123]


' Yes, bc both refers to the same data. When we change the value in v2 wich is a view of v1 it will affect v1'